In [1]:
score = 50

if score > 50:
  print("P")
else:
  print("NP")

NP


In [2]:
def fact(n):
  mult = 1
  for k in range(2, n+1):
    mult = mult*k
  return mult

fact(5)

120

In [3]:
import numpy as np

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [4]:
x = np.array([1, 2, 3, 4])
y = np.array([2, 3, 4, 5])
print(x)
print(type(x))
print(y)
print(x*y)

y = y.T
print(y)

print(x*y)

[1 2 3 4]
<class 'numpy.ndarray'>
[2 3 4 5]
[ 2  6 12 20]
[2 3 4 5]
[ 2  6 12 20]


In [5]:
a = np.array([[1, 2],
             [3, 4]])

b = np.array([[1, 0],
              [0, 4]])

print(a*b)

[[ 1  0]
 [ 0 16]]
