# Week1


In [ ]:
fact = 1
for i in range(20, 0, -1):
  fact = fact*i
print(fact)


2432902008176640000


# Week2


In [ ]:
score = 50

if score > 50:
  print("P")
else:
  print("NP")

NP


In [ ]:
def fact(n):
  mult = 1
  for k in range(2, n+1):
    mult = mult*k
  return mult

fact(5)

120

In [ ]:
import numpy as np

In [ ]:
x = np.array([1, 2, 3, 4])
y = np.array([2, 3, 4, 5])
print(x)
print(type(x))
print(y)
print(x*y)

y = y.T
print(y)

print(x*y)

[1 2 3 4]
<class 'numpy.ndarray'>
[2 3 4 5]
[ 2  6 12 20]
[2 3 4 5]
[ 2  6 12 20]


In [ ]:
a = np.array([[1, 2],
             [3, 4]])

b = np.array([[1, 0],
              [0, 4]])

print(a*b)



[[ 1  0]
 [ 0 16]]


# Week5

In [ ]:
# Initialize
x0, y0 = 1.0, 2.0
eps = 1e-8
t = 1e-3
# t가 커질수록 더 빨리 수렴함

In [ ]:
# GD
xk, yk = x0, y0
k = 0

while True:
  tk = t
  # 1. delta xk = -grad f(xk)
  delta_xk = -xk + 2*yk
  delta_yk = 2*xk - 8*yk
  # 2. xkp1 = xk + tk*(delta xk)
  xkp1 = xk + tk*delta_xk
  ykp1 = yk + tk*delta_yk

  if (xkp1 - xk)**2 + (ykp1 - yk)**2 < eps**2:
    print("Converge at iter = ", k)
    break

  xk, yk = xkp1, ykp1

  k += 1

Converge at iter =  23770


In [ ]:
print(xk)
print(yk)

2.060815521374836e-05
5.472793138485839e-06


# Week5

In [ ]:
# GD
xk, yk = x0, y0
k = 0

while True:
  # 0. Exact line search (t = gTg/gTAg)
  gTg = (-xk + 2*yk)**2 + (2*xk - 8*yk)**2
  gTAg = (-xk + 2*yk)**2 - 4*(-xk + 2*yk)*(2*xk - 8*yk) + 8*(2*xk - 8*yk)**2
  tk = gTg/gTAg

  # 1. delta xk = -grad f(xk)
  delta_xk = -xk + 2*yk
  delta_yk = 2*xk - 8*yk
  # 2. xkp1 = xk + tk*(delta xk)
  xkp1 = xk + tk*delta_xk
  ykp1 = yk + tk*delta_yk

  if (xkp1 - xk)**2 + (ykp1 - yk)**2 < eps**2:
    print("Converge at iter = ", k)
    break

  xk, yk = xkp1, ykp1

  k += 1

Converge at iter =  12


In [ ]:
print(xk)
print(yk)

2.4339253618541953e-09
4.86785072370809e-09


In [ ]:
def f(x, y):
  return 0.5*(x**2 - 4*x*y + 8*y**2)

x0, y0 = 1.0, 2.0
eps = 1e-8
t = 1.0
alpha, beta = 0.3, 0.9

In [ ]:
# GD
xk, yk = x0, y0
k = 0

while True:
  # 0. Backtracking line search
  # 1. delta xk = -grad f(xk)
  delta_xk = -xk + 2*yk
  delta_yk = 2*xk - 8*yk

  tk = 1
  while True:
    LHS = f(xk+tk*delta_xk, yk+tk*delta_yk)
    RHS = f(xk, yk)-tk*alpha*(delta_xk**2 + delta_yk**2)

    if LHS < RHS: break
    tk = beta*tk

  # 2. xkp1 = xk + tk*(delta xk)
  xkp1 = xk + tk*delta_xk
  ykp1 = yk + tk*delta_yk

  if (xkp1 - xk)**2 + (ykp1 - yk)**2 < eps**2:
    print("Converge at iter = ", k)
    break

  xk, yk = xkp1, ykp1

  k += 1

Converge at iter =  157


In [ ]:
print(xk)
print(yk)

4.708333166538079e-08
7.895305313707068e-09


In [ ]:
4.02